### ISSUE TITLE
Is there any reason you are not reacting to server returning 401 when using access token?

### ISSUE THREAD

**Issue by claudioredi** [msasikanth/tweet-unroll-android#5]
First, thanks for sharing all this. It really helped me to integrate a SSO using AppAuth!

Hopefully I didn't miss it since I'm just starting with Kotlin and returning after many years to Android native development but haven't seen any code to refresh the token in case server returns 401 to a request using stored token. 

Although I see you check for token validity client side, I'm used to rely on server to tell me that so in the worst case I was expecting logic to ensure you properly react to this situation.

If I missed it, sorry :) If I'm correct I would be interested to know why you didn't include it. I can definitively help with a pull request if you tell me that it's on your TODO list.

**Comment by msasikanth** [comment]
AppAuth `[AuthorizationException](https://openid.github.io/AppAuth-Android/docs/latest/net/openid/appauth/AuthorizationException.html)` provides variables to get the error code and status. I am not handling individual errors at that point that's all. But I think you can have a conditional cause to handle errors depending on the error code if you want.
